export const BUTTON_LABELS = {
  Buttons: [
    {
      label: "7",
      value: "7",
      color: "bg-gray-600",
      type: "number",
    },
    {
      label: "8",
      value: "8",
      color: "bg-gray-600",
      type: "number",
    },
    {
      label: "9",
      value: "9",
      color: "bg-gray-600",
      type: "number",
    },
    {
      label: "AC",
      value: "AC",
      color: "bg-gray-500",
      type: "clear",
    },
    {
      label: "/",
      value: "/",
      color: "bg-amber-500",
      type: "operator",
    },
    {
      label: "4",
      value: "4",
      color: "bg-gray-600",
      type: "number",
    },
    {
      label: "5",
      value: "5",
      color: "bg-gray-600",
      type: "number",
    },
    {
      label: "6",
      value: "6",
      color: "bg-gray-600",
      type: "number",
    },
    {
      label: "+/-",
      value: "-",
      color: "bg-gray-500",
      type: "operator",
    },
    {
      label: "X",
      value: "*",
      color: "bg-amber-500",
      type: "operator",
    },
    {
      label: "1",
      value: "1",
      color: "bg-gray-600",
      type: "number",
    },
    {
      label: "2",
      value: "2",
      color: "bg-gray-600",
      type: "number",
    },
    {
      label: "3",
      value: "3",
      color: "bg-gray-600",
      type: "number",
    },
    {
      label: "%",
      value: "%",
      color: "bg-gray-500",
      type: "operator",
    },
    {
      label: "-",
      value: "-",
      color: "bg-amber-500",
      type: "operator",
    },
    {
      label: "00",
      value: "00",
      color: "bg-gray-600",
      type: "number",
    },
    {
      label: "0",
      value: "0",
      color: "bg-gray-600",
      type: "number",
    },
    {
      label: ".",
      value: ".",
      color: "bg-gray-600",
      type: "number",
    },
    {
      label: "=",
      value: "=",
      color: "bg-amber-500",
      type: "operator",
    },
    {
      label: "+",
      value: "+",
      color: "bg-amber-500",
      type: "operator",
    },
  ],
};
